version: '2'

services:
  csgoserver:
    build: .
     image: andiwand/csgoserver
    container_name: csgoserver
    restart: always
    ports:
      - "27015:27015"
    volumes:
      - steam-bin:/var/lib/steam
      - csgo-bin:/var/lib/csgo
      - csgo-cfg:/var/lib/csgo/csgo/cfg

volumes:
  steam-bin:
  csgo-bin:
  csgo-cfg:
