version: '2'

services:
  csgoserver:
    container_name: csgoserver
    image: andiwand/csgoserver
    restart: always
    ports:
      - "27015:27015"
    volumes:
      - steam-bin:/var/lib/steam
      - csgo-bin:/var/lib/csgo
      - csgo-cfg:/var/lib/csgo/csgo/cfg

volumes:
  steam-bin:
    external: false
  csgo-bin:
    external: false
  csgo-cfg:
    external: false
